- name: Debug via SSH
  uses: ./  # sau username/repo@main
  with:
    SSH_PASS: ${{ secrets.SSH_PASS }}
    NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    NGROK_REGION: eu          # opțional
    NGROK_TIMEOUT: 1800       # 30 minute
